In [14]:
import pandas as pd
df = pd.DataFrame(
     {
         "foo": ["one", "one", "one", "two", "two", "two"],
         "bar": ["A", "B", "C", "A", "B", "C"],
         "baz": [1, 2, 3, 4, 5, 6],
         "zoo": ["x", "y", "z", "q", "w", "t"],
     }
 )
df1 = pd.DataFrame(
     {
         "foo": ["one1", "one1", "one1", "two1", "two1", "two1"],
         "bar": ["A1", "B1", "C1", "A1", "B1", "C1"],
         "baz": [1, 2, 3, 4, 5, 6],
         "zoo": ["x", "y", "z", "q", "w", "t"],
     }
 )
result = pd.concat([df1,df])
result

    foo bar  baz zoo
0  one1  A1    1   x
1  one1  B1    2   y
2  one1  C1    3   z
3  two1  A1    4   q
4  two1  B1    5   w
5  two1  C1    6   t
0   one   A    1   x
1   one   B    2   y
2   one   C    3   z
3   two   A    4   q
4   two   B    5   w
5   two   C    6   t

In [17]:
#Join two data frames join="outerjoin"
pd.concat([df,df1],axis=1)

   foo bar  baz zoo   foo bar  baz zoo
0  one   A    1   x  one1  A1    1   x
1  one   B    2   y  one1  B1    2   y
2  one   C    3   z  one1  C1    3   z
3  two   A    4   q  two1  A1    4   q
4  two   B    5   w  two1  B1    5   w
5  two   C    6   t  two1  C1    6   t

In [21]:
#Inner join
result = pd.concat([df, df1], axis=1, join="inner")
result

   foo bar  baz zoo   foo bar  baz zoo
0  one   A    1   x  one1  A1    1   x
1  one   B    2   y  one1  B1    2   y
2  one   C    3   z  one1  C1    3   z
3  two   A    4   q  two1  A1    4   q
4  two   B    5   w  two1  B1    5   w
5  two   C    6   t  two1  C1    6   t